# History file easy to script-update
0.8:
  - initial organization of Orgie Project
0.9:
  - this would be the first
  - 20110110 082218 LogT41bis added history
  - 20110110 082313 LogT41bis non saprei deploy
  - 20110110 082419 LogT41bis Created gh-pages in other repository (this is master btw)
  - 20110110 083355 LogT41bis changed history for creating ghpags
