## YAML Template.
## $Id: secrets.yml 1661 2009-07-23 11:25:02Z rcarlesso $
#
# This is going to change on host machines (i.e. production)
# On the footer there will be a warning saying: Please change file 'secrets.yml' in productin if you want o see this message disappear

# YOU HAVE TO CONFIGURE CAPISTRANO NOT TO OVERWRITE ON STAGING MACHINES!!!


#secret_svn_id: "$Id: secrets.yml 1661 2009-07-23 11:25:02Z rcarlesso $"
testusers_salt: qwerty-hansel
root_pass: hansel-asdfgh
#footer_warning: AAA
#secret-test-string: 'Change this string! If you dont, the production env will inherit all the passwords from SVN and test installations. If you change the password here, the system will have a different password... '
#description: 'Overridden by secrets.yml ;)'
